### ISSUE TITLE
Read config from JSON or YAML file

### ISSUE THREAD

**Issue by bbibentyo** [dcu/mongodb_exporter#116]
Just in case this feature is not yet there, It would be nice if we can pass put all the configuration into a file and pass file when starting the process. It's better than having to manually type the password, which makes it visible to all who have access to the server.

`./mongodb_exporter -config-file=/etc/some_file.json`

**Comment by wireless00** [comment]
Is it now possible ? It seem's to me that using a config file (.json or .yaml) is a valid request.
1 year and no update ?

I see no commit for 2 years now.... May be Prometheus should remove this exporter from the recommanded exporters.......

**Comment by wireless00** [comment]
ok. It seem someone forked this repo and enhanced the tool.
You can find it here: There is active developement on it.
https://github.com/percona/mongodb_exporter
