### ISSUE TITLE
Metrics don't seem right

### ISSUE THREAD

**Issue by jeinwag** [dcu/mongodb_exporter#12]
I'm running mongodb_exporter on a three node mongodb cluster, so there are thee instances of mongodb_exporter which are being scraped by prometheus.
It looks as at least some of the metrics rerieved by mongodb_exporter are not correct. Let's consider mongodb_op_counters_repl_total, mongodb_exporter is given the exact same value on all three servers:

     mongodb_op_counters_repl_total{type="command"} 1
     mongodb_op_counters_repl_total{type="delete"} 20194
     mongodb_op_counters_repl_total{type="getmore"} 0
     mongodb_op_counters_repl_total{type="insert"} 40110
     mongodb_op_counters_repl_total{type="query"} 0
     mongodb_op_counters_repl_total{type="update"} 158048

But db.serverStatus() in mongo shell gives different values
On server 1:

    "opcountersRepl" : {
                    "insert" : 11187,
                    "query" : 0,
                    "update" : 88010,
                    "delete" : 8595,
                    "getmore" : 0,
                    "command" : 1
            },

On server 2:

    "opcountersRepl" : {
                    "insert" : 40110,
                    "query" : 0,
                    "update" : 158054,
                    "delete" : 20194,
                    "getmore" : 0,
                    "command" : 1
            },

On server 3:

    "opcountersRepl" : {
                    "insert" : 28948,
                    "query" : 0,
                    "update" : 70113,
                    "delete" : 11600,
                    "getmore" : 0,
                    "command" : 0
            },

It looks like all three exporter instances return values from server 2 (which is currenlty not the primary, btw).

Maybe I'm having some fundamental misunderstanding?

**Comment by zwopiR** [comment]
you hit a mongodb "feature": it returns the status of one arbitrary replica node. Try appending "?connect=direct" to the exporter URL parameter

**Comment by zwopiR** [comment]
If it helps, we should consider to hardcode it into the exporter. So please give Feedback on the issue.

**Comment by jeinwag** [comment]
Thanks for the quick feedback, appending "?connect=direct" fixed the issue, everything looks good now!
