### ISSUE TITLE
./mongodb_exporter.go:39: r.BasicAuth undefined 

### ISSUE THREAD

**Issue by parkhyeonghwa** [dcu/mongodb_exporter#13]
Hi -
Could you please advise on the below.

[root@localhost:~/go/packages/src/github.com/dcu/mongodb_exporter]# go build
# github.com/dcu/mongodb_exporter

./mongodb_exporter.go:39: r.BasicAuth undefined (type *http.Request has no field or method BasicAuth)

Hope to get an advise at the earliest.

Thanks!

**Comment by dcu** [comment]
hi, what's your `go version` ?

**Comment by nemocean** [comment]
the same issue
go version go1.2.1 linux/amd64

**Comment by czgarrett** [comment]
Having the same issue.  What's the required go version?

**Comment by tcaxias** [comment]
It's working for me with go 1.6

**Comment by deepthawtz** [comment]
@dcu should there be a minimum Go version (and documentation)? Or add support for older too?

**Comment by dcu** [comment]
@deepthawtz I think we should just set a minimum Go version, do you want to clarify that in the README file?

**Comment by deepthawtz** [comment]
sounds good to me 👍
