### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by MrMMorris** [dcu/mongodb_exporter#2]
Are there plans to have a docker image for this lovely exporter?

Here is an example: https://github.com/docker-infra/container_exporter/blob/master/Dockerfile

Let me know if you want me to help with anything :wink:

**Comment by dcu** [comment]
hi @MrMMorris 
you are welcome to help! I just added you to the repo as collaborator with push permissions

**Comment by MrMMorris** [comment]
Done! Do you have a docker hub account? or should I put it on mine? I don't want to steal any of your thunder :wink:

**Comment by dcu** [comment]
go ahead Marcus, you can use yours

**Comment by checketts** [comment]
Did this get pushed to Docker hub?

**Comment by OmgImAlexis** [comment]
@dcu can you please create a docker hub account and setup an automated build.

**Comment by setevoy2** [comment]
Hi there. Any updates with Docker image on Docker Hub?

**Comment by mrhnrk** [comment]
Example one: https://hub.docker.com/r/loefflefarn/dcu_mongo_exporter
