### ISSUE TITLE
SASL Authentication failed

### ISSUE THREAD

**Issue by vic3lord** [dcu/mongodb_exporter#21]
Hi,

I cannot connect to MongoDB instance that has authentication enabled in it.
MongoDB version 3.2.6, Debian Wheezy.

Best regards

**Comment by dcu** [comment]
@vic3lord do you have more details about this? you should be able to pass the credentials in the mongo uri

**Comment by vic3lord** [comment]
I have passed the credentials through URI still get the same error

**Comment by dcu** [comment]
are the credentials in a different db? are you passing `authSource` in the url? what do you see in the mongodb log?
we need more details to be able to debug what's happening.

**Comment by vic3lord** [comment]
I'm sorry, but I don't have that kind of information, I'd love to help out but don't work on it anymore... would love to know the answer for the future though...

Thanks
