### ISSUE TITLE
metrics broken down by mongodb host

### ISSUE THREAD

**Issue by deepthawtz** [dcu/mongodb_exporter#27]
When providing a `-mongodb.uri` argument w/ multiple hosts there is no breakdown of metrics per host/instance, only aggregate.

Not sure if this is a problem for anyone else but I think it would be nice to see which host in sharded cluster is experiencing issues (cpu, memory, etc).

Are there workarounds or plans to add an `instance` label to metrics?

**Comment by jasonparekh** [comment]
@deepthawtz curious, what was your solution for this?

**Comment by deepthawtz** [comment]
didn't really solve, I just decided there are probably enough indicators of cluster health w/o cpu metrics for each host
