### ISSUE TITLE
index_counters.go:35: too many errors

### ISSUE THREAD

**Issue by ZOXEXIVO** [dcu/mongodb_exporter#40]
Can't build exporter with Go 1.73

**Comment by wolfencom** [comment]
I'm having this same problem.

# github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod
collector/mongod/asserts.go:26: assertsTotal.WithLabelValues("regular").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/asserts.go:27: assertsTotal.WithLabelValues("warning").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/asserts.go:28: assertsTotal.WithLabelValues("msg").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/asserts.go:29: assertsTotal.WithLabelValues("user").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/asserts.go:30: assertsTotal.WithLabelValues("rollovers").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/background_flushing.go:53: backgroundFlushingflushesTotal.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/background_flushing.go:54: backgroundFlushingtotalMilliseconds.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/connections.go:36: connectionsMetricsCreatedTotal.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/global_lock.go:79: globalLockTotal.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/index_counters.go:35: indexCountersTotal.WithLabelValues("accesses").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongod/index_counters.go:35: too many errors
# github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongos
collector/mongos/asserts.go:26: assertsTotal.WithLabelValues("regular").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/asserts.go:27: assertsTotal.WithLabelValues("warning").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/asserts.go:28: assertsTotal.WithLabelValues("msg").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/asserts.go:29: assertsTotal.WithLabelValues("user").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/asserts.go:30: assertsTotal.WithLabelValues("rollovers").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/connections.go:36: connectionsMetricsCreatedTotal.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/metrics.go:60: metricsGetLastErrorWtimeTotalMilliseconds.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/metrics.go:62: metricsGetLastErrorWtimeoutsTotal.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/metrics.go:80: metricsCursorTimedOutTotal.Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/network.go:32: networkBytesTotal.WithLabelValues("in_bytes").Set undefined (type prometheus.Counter has no field or method Set)
collector/mongos/network.go:32: too many errors


I've tried on coreos 1122.3.0, and Ubuntu 16.10. It happens both when checking out the code and doing a simple make build, and when trying to do a docker build.

**Comment by deepthawtz** [comment]
this has nothing to do w/ Go version... It looks like the Prometheus Golang client changed up and the version was not pinned so these broke...

Updating to work w/ the latest version...

**Comment by arthur-c** [comment]
Hi, https://github.com/dcu/mongodb_exporter/pull/44 is not solving the problem for me.

```
go version
go version go1.6.3 linux/amd64
```

```
go get -u github.com/dcu/mongodb_exporter                                          
# github.com/dcu/mongodb_exporter/collector
workspace/go/src/github.com/dcu/mongodb_exporter/collector/asserts.go:26: assertsTotal.WithLabelValues("regular").Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/asserts.go:27: assertsTotal.WithLabelValues("warning").Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/asserts.go:28: assertsTotal.WithLabelValues("msg").Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/asserts.go:29: assertsTotal.WithLabelValues("user").Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/asserts.go:30: assertsTotal.WithLabelValues("rollovers").Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/background_flushing.go:53: backgroundFlushingflushesTotal.Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/background_flushing.go:54: backgroundFlushingtotalMilliseconds.Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/connections.go:36: connectionsMetricsCreatedTotal.Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/global_lock.go:79: globalLockTotal.Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/index_counters.go:35: indexCountersTotal.WithLabelValues("accesses").Set undefined (type prometheus.Counter has no field or method Set)
workspace/go/src/github.com/dcu/mongodb_exporter/collector/index_counters.go:35: too many errors

```

**Comment by deepthawtz** [comment]
#44 was never merged, that's why the compile issues still exist...

we'll have to pin the version of prometheus client in order for what's on master to work

**Comment by bamarni** [comment]
@deepthawtz : I've submitted a PR to vendor prometheus client to v0.8.0, using gopkg.in would have been the best option but unfortunately that didn't work, I think because of the underscore in the prometheus client repo.
