### ISSUE TITLE
Multiple gauge entries for replset members

### ISSUE THREAD

**Issue by georgelee1** [dcu/mongodb_exporter#50]
In [`replset_status.go`](https://github.com/dcu/mongodb_exporter/blob/master/collector/replset_status.go#L164) `state` is being included as part of the label which can result in multiple gauge entries for a single host if it changes status.

For example, when a node has become unreachable it's state is set as `"(not reachable/healthy)"`. When it reverts to it's usual `"PRIMARY"` or `"SECONDARY"` the old entry for the not reachable status persists in the `/metrics` endpoint.

```
mongodb_replset_member_health{name="<mongodbhost>",set="<myreplset>",state="(not reachable/healthy)"} 0
mongodb_replset_member_health{name="<mongodbhost>",set="<myreplset>",state="SECONDARY"} 1
```

`state` should be part of the label for the replset gauges as it is a changeable value.

**Comment by deepthawtz** [comment]
@georgelee1 we'll be getting on this issue this week

**Comment by georgelee1** [comment]
Nice. I created a PR a while back if that helps.
