### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by fevlake** [dcu/mongodb_exporter#52]
Hello!

Does anybody have grafana dashboard for that exporter?

It will be really cool if somebody can share it.

Thanks a lot!

**Comment by ItsLachy** [comment]
https://github.com/percona/grafana-dashboards

**Comment by MathieuMailhos** [comment]
Maybe it's me but this Percona's MongoDB Overview Dashboard does not show anything.
Is it supposed to only work with Percon'as MongoDB exporter?

**Comment by saada** [comment]
Made a PR https://github.com/dcu/mongodb_exporter/pull/61

**Comment by dcu** [comment]
thanks @saada !

**Comment by mehrdadhosseinzadeh** [comment]
i am using percona mongodb_exporter
all metrics prefix is mongodb_ss
but does not any dashboard in grafana show visualation
please help
@saada 
@dcu

**Comment by slashclash** [comment]
[mehrdadhosseinzadeh](https://github.com/mehrdadhosseinzadeh), you can try to use --compatible-mode flag when starting the exporter.
