### ISSUE TITLE
Get replication lag in an easy way

### ISSUE THREAD

**Issue by zhihuiFan** [dcu/mongodb_exporter#58]
Currently we have some metrics like

```
mongodb_replset_member_optime_date{name="a:27017",set="stgResource",state="SECONDARY"} 1.494836609e+09
mongodb_replset_member_optime_date{name="b:27017",set="stgResource",state="PRIMARY"} 1.494836609e+09
```

but I can't the the replication lag easily with Prometheus recording rule.   Do you have any suggestion on this?

is it ok to expose the replication_lag for current instance directly? 

Thanks

**Comment by zhihuiFan** [comment]
@dcu could you have a look at this?

**Comment by dcu** [comment]
@zhihuiFan sure, just a minor typo fix is needed
