### ISSUE TITLE
Stale/wrong values for (at least) mongodb_network_bytes_total

### ISSUE THREAD

**Issue by discordianfish** [dcu/mongodb_exporter#7]
Hi,

I'm trying to use the mongodb_exporter but realize some odd issues. It's somehow not exposing the actual numbers for the mongodb_network_bytes_total sometimes. This is the output of `curl`ing the exporter every second:

```
mongodb_network_bytes_total{state="in_bytes"} 1.8038162909e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038213018e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038257311e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038289814e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038336711e+10
mongodb_network_bytes_total{state="in_bytes"} 1.22594549377e+11
mongodb_network_bytes_total{state="in_bytes"} 1.803846286e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038546902e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038588227e+10
mongodb_network_bytes_total{state="in_bytes"} 1.8038659031e+10
mongodb_network_bytes_total{state="in_bytes"} 4.974604715e+09
mongodb_network_bytes_total{state="in_bytes"} 5.00446282153e+11
mongodb_network_bytes_total{state="in_bytes"} 5.00446395761e+11
mongodb_network_bytes_total{state="in_bytes"} 4.974617148e+09
mongodb_network_bytes_total{state="in_bytes"} 5.00446665747e+11
mongodb_network_bytes_total{state="in_bytes"} 1.8039037928e+10
mongodb_network_bytes_total{state="in_bytes"} 5.00446920076e+11
mongodb_network_bytes_total{state="in_bytes"} 1.22597290424e+11
```

I've checked mongodb and those aren't counter resets or something. I suspect there is some issues with the `shared/`, maybe it creates two counters with the same name or something.
Will investigate this more next week.

**Comment by dcu** [comment]
weird, it's working fine on my side. did you restart the mongodb server?

Please let me know if you find what's causing the issue

**Comment by discordianfish** [comment]
@dcu No it didn't restart. And I also saw the issue with other metrics. In general lot of numbers seems to be off. I've checked the stats in mongodb via the mongo shell and they look correct, so it really seems like an issue with the exporter.

**Comment by dcu** [comment]
How's your setup? Replica set? Sharded? MongoDB version?

Also can you post an example of the exporter data vs db status data?

Thanks

**Comment by discordianfish** [comment]
It's mongodb 2.6.9, 5 shards with 4 replicas each running on AWS. Here is the exporter and mongo cli output from the same time (<1s between):

- https://gist.github.com/discordianfish/38c80b18364bc52b83df All good here
- https://gist.github.com/discordianfish/a04db20657e8bda951d0 Differences of bytesIn vs in_bytes

When run in a loop and watching for the in_bytes counter this gets more apparent:
```
while true; do echo 'db.runCommand({ serverStatus: 1 })' | mongo 127.0.0.1:27018 | grep bytesIn; curl -s localhost:9101/metrics|grep in_bytes; sleep 1; done
		"bytesIn" : 7838867496,
mongodb_network_bytes_total{state="in_bytes"} 5.177120978e+10
		"bytesIn" : 7838938811,
mongodb_network_bytes_total{state="in_bytes"} 1.0905279525e+11
		"bytesIn" : 7838984875,
mongodb_network_bytes_total{state="in_bytes"} 1.09052946269e+11
		"bytesIn" : 7838996774,
mongodb_network_bytes_total{state="in_bytes"} 1.0905312077e+11
		"bytesIn" : 7839051215,
mongodb_network_bytes_total{state="in_bytes"} 1.09053300953e+11

		"bytesIn" : 7839078104,
mongodb_network_bytes_total{state="in_bytes"} 1.09053478539e+11
		"bytesIn" : 7839116593,
mongodb_network_bytes_total{state="in_bytes"} 7.839116978e+09
		"bytesIn" : 7839173216,
mongodb_network_bytes_total{state="in_bytes"} 1.09053974839e+11
		"bytesIn" : 7839230920,
mongodb_network_bytes_total{state="in_bytes"} 1.0905413353e+11
```

The exporter also isn't logging anything.

**Comment by discordianfish** [comment]
@dcu General question: Are you still using this exporter and plan to maintain it in the future? It looks like it's not working with mongodb 3.2 and the code isn't very go idiomatic so I would rather refactor it first before adding support for mongodb 3.2 and fixing this issue here.

**Comment by dcu** [comment]
@discordianfish I added you as collaborator to the repo, feel free to refactor it

**Comment by percona-services-ro** [comment]
@discordianfish  We should sync up I was going to start adding more metrics for replSet's and Sharding/mongos. Would like to work with you on your refactors so I take those into account before I do a pull request :)

**Comment by dbmurphy** [comment]
@discordianfish We should sync up I was going to start adding more metrics for replSet's and Sharding/mongos. Would like to work with you on your refactors so I take those into account before I do a pull request :)

**Comment by discordianfish** [comment]
I just looked into refactoring it but I tend to rewrite it in a simpler way. I get that the dynamic configuration of 'interesting' values via the groups.yaml and things like that are nice but also make everything quite complex.

**Comment by dbmurphy** [comment]
I think the yaml way while complex lends more toward Ansible integration wouldn't you say?  If you can think of another methodology I am curious. But I do see your point simple and clean interfaces are nice. I think there are two phases here  1) Refactor to be cleaner ( not me im not that good at go yet)  2) Expand the tool to support the entire mongo system not just stand alone nodes.  When do you think you might get to 1, so I know when I can get my team helping on 2? No rush just trying to plan resources.

**Comment by discordianfish** [comment]
Looks like @dcu started refactoring the code. That's great! Then I'll hold off with that for now and see if I can contribute to this code base after the refactoring is done.

@dcu If you have prometheus related questions, I'm happy to help!

**Comment by discordianfish** [comment]
Just FYI: I built a new sharded cluster, this time with mongo 3.2 and there metrics look much more reasonable.

I also confirmed that with current master, I still have the same problem on our old cluster.

**Comment by dcu** [comment]
@discordianfish are you passing more than one host in the URI parameter?

**Comment by dcu** [comment]
I think this was resolved with the commit from March 7. Please reopen if it is not.
