### ISSUE TITLE
Error during `Docker build`

### ISSUE THREAD

**Issue by f4rx** [dcu/mongodb_exporter#85]
Hello, I'm getting an error during `Docker build`
```
git clone https://github.com/dcu/mongodb_exporter.git
cd mongodb_exporter
$ docker build -t mongodb_exporter .
...
Step 5/11 : RUN cd /go/src/github.com/dcu/mongodb_exporter && make release
 ---> Running in fc15077416cc
glide install
...
[INFO]	Replacing existing vendor dependencies
mkdir -p release
perl -p -i -e 's/{{VERSION}}/v1.0.0/g' mongodb_exporter.go
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/{{ <-- HERE VERSION}}/ at -e line 1.
make: *** [Makefile:19: release] Error 255
The command '/bin/sh -c cd /go/src/github.com/dcu/mongodb_exporter && make release' returned a non-zero code: 2
```

**Comment by avishefi** [comment]
Perl requires escaping '{' characters since around version 5.22:
http://search.cpan.org/dist/perl-5.22.0/pod/perldelta.pod#A_literal_%22%7B%22_should_now_be_escaped_in_a_pattern

**Comment by Samith88** [comment]
Update following 2 lines in mongodb_exporter/Makefile,

perl -p -i -e 's/\{\{VERSION}}/$(TAG)/g' mongodb_exporter.go
perl -p -i -e 's/$(TAG)/\{\{VERSION}}/g' mongodb_exporter.go

**Comment by supriyopaul** [comment]
Is this fix done? I'm still getting the error
![image](https://user-images.githubusercontent.com/33823698/40038837-b7f10ba0-5831-11e8-9dc2-1d7351e58d12.png)
