### ISSUE TITLE
Not seeing the correct stats

### ISSUE THREAD

**Issue by fgraichen** [dcu/mongodb_exporter#96]
I am not seeing any of the stats for the actual database..
examples of what I am seeing..  NO OP counters etc  -  Do I need to create an ID that can get the stats  see startup below..

http_response_size_bytes{handler="prometheus",quantile="0.5"} 1365
http_response_size_bytes{handler="prometheus",quantile="0.9"} 1368
http_response_size_bytes{handler="prometheus",quantile="0.99"} 1368
http_response_size_bytes_sum{handler="prometheus"} 34427
http_response_size_bytes_count{handler="prometheus"} 22
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.09
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 9.928704e+06
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.52547184559e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge

./mongodb_exporter-linux-amd64 -groups.enabled 'asserts,durability,background_flusshing,connections,extra_info,global_lock,index_counters,network,op_counters,op_counters_repl,memory,locks,metrics' -mongodb.collect.database -mongodb.collect.oplog -logtostderr -mongodb.tls-disable-hostname-validation -mongodb.uri mongdb:/admin:notrealpasswordnospecialcharacters@127.0.0.1:27017

I am seeing this message in the log.

6773 connection.go:48] Cannot connect to server using url mongdb:/admin:notrealpassword@127.0.0.1:27017: server returned error on SASL authentication step: Authentication failed.

**Comment by fgraichen** [comment]
I had two errors in the db url..  took way to long to notice..closing issue

**Comment by LzxUser** [comment]
I want to know what problem you found and how to solve it，
server returned error on SASL authentication step: Authentication failed.
I have the same problem
